In [6]:
import numpy as np

In [7]:
data1 =[[1,2,3,4],[5,6,7,8]]

In [8]:
data1

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [9]:
#converting to the array
arr1 = np.array(data1)

In [10]:
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [11]:
#for chaking dimensions of array 
arr1.ndim

2

In [12]:
# for finding the shape of array
arr1.shape

(2, 4)

In [13]:
#in above output (2 ,4) means 2 rows and 4 coloum

In [14]:
#for checking types of data in array
arr1.dtype

dtype('int32')

In [15]:
# for storing in zero matrix
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [16]:
# for aranging array
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
#storing in second array
arr2 = np.arange(10)

In [18]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
arr2[5:8]

array([5, 6, 7])

In [20]:
# replace 5th postion to th postion by 12
arr2[5:8] = 12

In [21]:
arr2

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [22]:
reshape_array = np.arange(25).reshape(5,5)

#here we are arange array of sequence of 25 nd reshape 

In [23]:
reshape_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [24]:
# for printing first row 
reshape_array[0]

array([0, 1, 2, 3, 4])

In [25]:
# for printing second row 
reshape_array[1]

array([5, 6, 7, 8, 9])

In [26]:
# for printing third row 
reshape_array[2]

array([10, 11, 12, 13, 14])

In [27]:
# for printing still second row 
reshape_array[0:2]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [28]:
# for printing after second row 
reshape_array[2:]

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [29]:
#for printing coloum
reshape_array[:,0:2]  #first 2 coloum wrritten 

array([[ 0,  1],
       [ 5,  6],
       [10, 11],
       [15, 16],
       [20, 21]])

In [30]:
reshape_array[:,0:3]  #first 3 coloum wrritten 

array([[ 0,  1,  2],
       [ 5,  6,  7],
       [10, 11, 12],
       [15, 16, 17],
       [20, 21, 22]])

In [31]:
# here check we have to write 4 rows and 3 coloum 
reshape_array[0:4,0:3] 

array([[ 0,  1,  2],
       [ 5,  6,  7],
       [10, 11, 12],
       [15, 16, 17]])

In [32]:
reshape_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [33]:
arr = np.arange(10)  # for printing a array in sequence
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
#finding square root of above arr
arr1 = np.sqrt(arr)
arr1

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [35]:
# Take a square of arr1
np.square(arr1)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [36]:
#syntax  : np.sign()   it prints sign of element if positive then 1 if nehgative then -1 like that
np.sign(arr1)

array([0., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [37]:
#floor- printing closer small value of int
np.floor(arr1)

array([0., 1., 1., 1., 2., 2., 2., 2., 2., 3.])

In [38]:
#ceil - printing larger value of int
np.ceil(arr1)

array([0., 1., 2., 2., 2., 3., 3., 3., 3., 3.])

In [39]:
# round - for round of if 1.4 and less to 1=1 and if 1.5 and above =2
np.round(arr1)

array([0., 1., 1., 2., 2., 2., 2., 3., 3., 3.])

In [40]:
np.log(arr1)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.34657359, 0.54930614, 0.69314718,
       0.80471896, 0.89587973, 0.97295507, 1.03972077, 1.09861229])

In [41]:
np.exp(arr1)

array([ 1.        ,  2.71828183,  4.11325038,  5.65223367,  7.3890561 ,
        9.35646902, 11.58243519, 14.09403011, 16.91882868, 20.08553692])

In [42]:
np.round(1.5)

2.0

In [43]:
a= [4,3,1]
a

[4, 3, 1]

In [44]:
b = [3,4,1]
b

[3, 4, 1]

In [45]:
# for adding both list
np.add(a,b)

array([7, 7, 2])

In [46]:
# for subtracting both list
np.subtract(a,b)

array([ 1, -1,  0])

In [47]:
#for multipling both the list
np.multiply(a,b)

array([12, 12,  1])

In [48]:
#for division both the list
np.divide(a,b)

array([1.33333333, 0.75      , 1.        ])

In [49]:
#mod
np.mod(a,b)

array([1, 3, 0], dtype=int32)

In [50]:
np.greater(a,b)

array([ True, False, False])

In [51]:
np.greater_equal(a,b)

array([ True, False,  True])

In [52]:
np.less(a,b)

array([False,  True, False])

In [53]:
np.less_equal(a,b)

array([False,  True,  True])

In [54]:
np.equal(a,b)

array([False, False,  True])

In [55]:
arrsts = np.array([[1,2,3],[4,5,6],[7,8,9]])
arrsts

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [56]:
arrsts.mean()

5.0

In [57]:
arrsts.sum()

45

In [58]:
arrsts.std()

2.581988897471611

In [59]:
arrsts.var()

6.666666666666667

In [60]:
a = np.array([[2,3,4],[5,6,7]])

In [61]:
z= np.zeros((2,3))

In [62]:
a

array([[2, 3, 4],
       [5, 6, 7]])

In [63]:
z

array([[0., 0., 0.],
       [0., 0., 0.]])

In [64]:
np.append(a,z,axis=0)

array([[2., 3., 4.],
       [5., 6., 7.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [65]:
np.append(a,z,axis=1)

array([[2., 3., 4., 0., 0., 0.],
       [5., 6., 7., 0., 0., 0.]])

In [66]:
import pandas as pd


In [69]:
data = pd.DataFrame(np.arange(16).reshape(4,4),index = ['ohio','colorado','utah','network'],columns =['one','two','three','four'])

In [70]:
data

one  two  three  four
ohio        0    1      2     3
colorado    4    5      6     7
utah        8    9     10    11
network    12   13     14    15

In [71]:
data['one']

ohio         0
colorado     4
utah         8
network     12
Name: one, dtype: int32

In [77]:
arrsts = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [76]:
#variation
arrsts.var()

6.666666666666667